name: pytest
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v1
      with:
        python-version: "3.12.2"
        allow-prereleases: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv codecov
        pip install -r requirements.txt
        pipenv install --dev
    - name: pull reference data
      run: |
        curl ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz -o tests/test_data/hs37d5.fa.gz
    - name: gunzip data
      run: |
        gunzip tests/test_data/*.gz
    - name: Test with pytest
      run: |
        pytest -vv --cov . --cov scripts/ --cov utils/